spring:
  application:
    name: hr-management
  profiles:
    default: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

app:
  cors:
    allowed-origins: http://localhost:8080,http://localhost:5500
