CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR(150) NOT NULL,
    gender VARCHAR(20),
    date_of_birth DATE,
    phone VARCHAR(20),
    email VARCHAR(150)
);

CREATE INDEX IF NOT EXISTS idx_employees_full_name ON employees(full_name);
CREATE INDEX IF NOT EXISTS idx_employees_email ON employees(email);
CREATE INDEX IF NOT EXISTS idx_employees_phone ON employees(phone);

ALTER TABLE employees DROP COLUMN IF EXISTS address;
ALTER TABLE employees DROP COLUMN IF EXISTS department;
ALTER TABLE employees DROP COLUMN IF EXISTS position;
ALTER TABLE employees DROP COLUMN IF EXISTS hire_date;
ALTER TABLE employees DROP COLUMN IF EXISTS status;
ALTER TABLE employees DROP COLUMN IF EXISTS base_salary;
ALTER TABLE employees DROP COLUMN IF EXISTS note;
ALTER TABLE employees DROP COLUMN IF EXISTS created_at;
ALTER TABLE employees DROP COLUMN IF EXISTS updated_at;
